In [123]:
# Import dependencies 
import pandas as pd

In [124]:
# Read in the datset and select only the columns that are needed relating to sleep data
sleep_df = pd.read_csv('sleep_analysis.csv', usecols =['date','Sleep Score','Sleep Score','Total Sleep Score','Restfulness Score','Total Sleep Duration', 'Total Bedtime ', 'Awake Time','REM Sleep Duration', 'Light Sleep Duration', 'Deep Sleep Duration','Bedtime Start','Move Every Hour Score','Sleep Balance Score'])

In [125]:
# Convert duration times from seconds to hours
sleep_df['Total Sleep Duration'] = sleep_df['Total Sleep Duration'] / 60**2
sleep_df['Awake Time'] = sleep_df['Awake Time'] / 60**2
sleep_df['Total Bedtime '] = sleep_df['Total Bedtime '] / 60**2
sleep_df['REM Sleep Duration'] = sleep_df['REM Sleep Duration'] / 60**2
sleep_df['Light Sleep Duration'] = sleep_df['Light Sleep Duration'] / 60**2
sleep_df['Deep Sleep Duration'] = sleep_df['Deep Sleep Duration'] / 60**2

In [126]:
sleep_df.sort_values(by=['date'],ascending=False)

,date,Sleep Score,Total Sleep Score,Restfulness Score,Total Sleep Duration,Total Bedtime,Awake Time,REM Sleep Duration,Light Sleep Duration,Deep Sleep Duration,Bedtime Start,Move Every Hour Score,Sleep Balance Score
128,2022-11-06,85.0,84.0,63.0,7.891667,8.883333,0.991667,1.800000,4.633333,1.458333,2022-11-05T22:35:00-08:00,95.0,85
127,2022-11-05,76.0,72.0,64.0,7.033333,8.483333,1.450000,1.808333,3.300000,1.925000,2022-11-05T00:06:50-07:00,95.0,82
126,2022-11-04,74.0,69.0,64.0,6.825000,8.200000,1.375000,1.708333,3.500000,1.616667,2022-11-03T22:11:53-07:00,100.0,84
125,2022-11-03,84.0,85.0,64.0,7.966667,9.050000,1.083333,2.375000,4.091667,1.500000,2022-11-02T22:06:54-07:00,100.0,87
124,2022-11-02,80.0,75.0,63.0,7.233333,8.733333,1.500000,1.808333,4.066667,1.358333,2022-11-01T22:02:45-07:00,100.0,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2022-06-26,86.0,100.0,69.0,11.250000,14.150000,2.900000,3.866667,6.783333,0.600000,2022-06-25T17:17:03-07:00,95.0,88
3,2022-06-25,57.0,50.0,49.0,5.491667,7.800000,2.308333,1.116667,3.325000,1.050000,2022-06-24T21:02:41-07:00,60.0,61
2,2022-06-24,69.0,58.0,66.0,6.008333,7.350000,1.341667,1.375000,3.458333,1.175000,2022-06-23T22:55:32-07:00,95.0,69
1,2022-06-23,70.0,69.0,67.0,6.841667,8.550000,1.708333,1.466667,4.583333,0.791667,2022-06-22T21:52:07-07:00,100.0,None
0,2022-06-22,77.0,77.0,70.0,7.358333,8.866667,1.508333,1.766667,4.075000,1.516667,2022-06-21T22:45:25-07:00,100.0,None

In [127]:
sleep_df.columns

Index(['date', 'Sleep Score', 'Total Sleep Score', 'Restfulness Score',
       'Total Sleep Duration', 'Total Bedtime ', 'Awake Time',
       'REM Sleep Duration', 'Light Sleep Duration', 'Deep Sleep Duration',
       'Bedtime Start', 'Move Every Hour Score', 'Sleep Balance Score'],
      dtype='object')